search:
  name: Search
  description: Emulates opening the search screen and entering the search keyword.
  target:
    entity:
      integration: casatunes
      domain: media_player
  fields:
    keyword:
      name: Keyword
      description: The keyword to search for.
      required: true
      example: "Pearl Jam"
      selector:
        text:
